name: mcts
channels:
  - conda-forge
dependencies:
  - python=3.7
  - scikit-learn=0.21.3
  - rdkit
  - pandas
  - seaborn
  - pip
  - pip:
    - pickle-mixin
    - git+https://github.com/mahendra-awale/medchem_moves
